import "./globals.css";
import ToolTip from "./components/ToolTipComponent";

export const metadata = {
  title: "AlgoVisualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`font-['Inter'] bg-[#041c32] flex flex-col w-full min-h-screen text-white`}
      >
        {children}
        <ToolTip />
      </body>
    </html>
  );
}
