import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/HeaderComponent";
import AlgoContextProvider from "../context/AlgoContext";
import AnimationProvider from "@/context/AnimationContext";

const mainfont = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "AlgoVisualizer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${mainfont.className} bg-[#041c32] flex flex-col w-full min-h-screen text-white`}
      >
        <Header />

        <AlgoContextProvider>
          <AnimationProvider>{children}</AnimationProvider>
        </AlgoContextProvider>
      </body>
    </html>
  );
}
